// Unit generated using the Delphi Wmi class generator tool, Copyright Rodrigo Ruz V. 2010
// WMI version 7600.16385
// Namespace root\CIMV2 Class Win32_SystemEnclosure
// MSDN info about this class http://msdn2.microsoft.com/library/default.asp?url=/library/en-us/wmisdk/wmi/Win32_SystemEnclosure.asp
unit uWin32_SystemEnclosure;

interface

uses

 Activex,
 ComObj,
 uWmiDelphiClass;

type
   ///<summary>
   ///The Win32_SystemEnclosure class represents the properties associated with a 
   ///physical system enclosure.
   ///</summary>
  TWin32_SystemEnclosure=class(TWmiClass)
  private
   FAudibleAlarm                       : Boolean;
   FBreachDescription                  : String;
   FCableManagementStrategy            : String;
   FCaption                            : String;
   FChassisTypes                       : Word;
   FCreationClassName                  : String;
   FCurrentRequiredOrProduced          : SmallInt;
   FDepth                              : Double;
   FDescription                        : String;
   FHeatGeneration                     : Word;
   FHeight                             : Double;
   FHotSwappable                       : Boolean;
   FInstallDate                        : TDateTime;
   FLockPresent                        : Boolean;
   FManufacturer                       : String;
   FModel                              : String;
   FName                               : String;
   FNumberOfPowerCords                 : Word;
   FOtherIdentifyingInfo               : String;
   FPartNumber                         : String;
   FPoweredOn                          : Boolean;
   FRemovable                          : Boolean;
   FReplaceable                        : Boolean;
   FSecurityBreach                     : Word;
   FSecurityStatus                     : Word;
   FSerialNumber                       : String;
   FServiceDescriptions                : String;
   FServicePhilosophy                  : Word;
   FSKU                                : String;
   FSMBIOSAssetTag                     : String;
   FStatus                             : String;
   FTag                                : String;
   FTypeDescriptions                   : String;
   FVersion                            : String;
   FVisibleAlarm                       : Boolean;
   FWeight                             : Double;
   FWidth                              : Double;
  public
   ///<summary>
   ///Boolean indicating whether the frame is equipped with an audible alarm.
   ///</summary>
   property AudibleAlarm : Boolean read FAudibleAlarm;
   ///<summary>
   ///BreachDescription is a free-form string providing more information if the 
   ///SecurityBreach property indicates that a breach or some other security-related 
   ///event occurred.
   ///</summary>
   property BreachDescription : String read FBreachDescription;
   ///<summary>
   ///CableManagementStrategy is a free-form string that contains information on how 
   ///the various cables are connected and bundled for the frame. With many 
   ///networking, storage-related and power cables, cable management can be a complex 
   ///and challenging endeavor. This string property contains information to aid in 
   ///assembly and service of the frame.
   ///</summary>
   property CableManagementStrategy : String read FCableManagementStrategy;
   ///<summary>
   ///The Caption property is a short textual description (one-line string) of the 
   ///object.
   ///</summary>
   property Caption : String read FCaption;
   ///<summary>
   ///An enumerated, integer-valued array indicating the type of chassis.
   ///</summary>
   property ChassisTypes : Word read FChassisTypes;
   ///<summary>
   ///CreationClassName indicates the name of the class or the subclass used in the 
   ///creation of an instance. When used with the other key properties of this class, 
   ///this property allows all instances of this class and its subclasses to be 
   ///uniquely identified.
   ///</summary>
   property CreationClassName : String read FCreationClassName;
   ///<summary>
   ///Current required by the chassis at 120V. If power is provided by the chassis 
   ///(as in the case of a UPS), this property may indicate the amperage produced, as 
   ///a negative number.
   ///</summary>
   property CurrentRequiredOrProduced : SmallInt read FCurrentRequiredOrProduced;
   ///<summary>
   ///The depth of the physical package in inches.
   ///</summary>
   property Depth : Double read FDepth;
   ///<summary>
   ///The Description property provides a textual description of the object. 
   ///</summary>
   property Description : String read FDescription;
   ///<summary>
   ///Amount of heat generated by the chassis in BTU/hour.
   ///</summary>
   property HeatGeneration : Word read FHeatGeneration;
   ///<summary>
   ///The height of the physical package in inches.
   ///</summary>
   property Height : Double read FHeight;
   ///<summary>
   ///A physical package can be hot swapped if it is possible to replace the element 
   ///with a physically different but equivalent one while the containing package has 
   ///power applied to it (i.e., is 'on').  For example, a disk drive package 
   ///inserted using SCA connectors is removable and can be hot swapped. All packages 
   ///that can be hot swapped are inherently removable and replaceable.
   ///</summary>
   property HotSwappable : Boolean read FHotSwappable;
   ///<summary>
   ///The InstallDate property is datetime value indicating when the object was 
   ///installed. A lack of a value does not indicate that the object is not installed.
   ///</summary>
   property InstallDate : TDateTime read FInstallDate;
   ///<summary>
   ///Boolean indicating whether the frame is protected with a lock.
   ///</summary>
   property LockPresent : Boolean read FLockPresent;
   ///<summary>
   ///The name of the organization responsible for producing the physical element. 
   ///This may be the entity from whom the element is purchased, but this is not 
   ///necessarily true. The latter information is contained in the Vendor property of 
   ///CIM_Product.
   ///</summary>
   property Manufacturer : String read FManufacturer;
   ///<summary>
   ///The name by which the physical element is generally known.
   ///</summary>
   property Model : String read FModel;
   ///<summary>
   ///The Name property defines the label by which the object is known. When 
   ///subclassed, the Name property can be overridden to be a Key property.
   ///</summary>
   property Name : String read FName;
   ///<summary>
   ///Integer indicating the number of power cords which must be connected to the 
   ///chassis, for all the components to operate.
   ///</summary>
   property NumberOfPowerCords : Word read FNumberOfPowerCords;
   ///<summary>
   ///OtherIdentifyingInfo captures additional data, beyond asset tag information, 
   ///that could be used to identify a physical element. One example is bar code data 
   ///associated with an element that also has an asset tag. Note that if only bar 
   ///code data is available and is unique/able to be used as an element key, this 
   ///property would be NULL and the bar code data used as the class key, in the tag 
   ///property.
   ///</summary>
   property OtherIdentifyingInfo : String read FOtherIdentifyingInfo;
   ///<summary>
   ///The part number assigned by the organization responsible for producing or 
   ///manufacturing the physical element.
   ///</summary>
   property PartNumber : String read FPartNumber;
   ///<summary>
   ///Boolean indicating that the physical element is powered on (TRUE), or is 
   ///currently off (FALSE).
   ///</summary>
   property PoweredOn : Boolean read FPoweredOn;
   ///<summary>
   ///A physical package is removable if it is designed to be taken in and out of the 
   ///physical container in which it is normally found, without impairing the 
   ///function of the overall packaging. A package can still be removable if power 
   ///must be 'off' in order to perform the removal. If power can be 'on' and the 
   ///package removed, then the element is removable and can be hot swapped. For 
   ///example, an extra battery in a laptop is removable, as is a disk drive package 
   ///inserted using SCA connectors. However, the latter can be hot swapped.  A 
   ///laptop's display is not removable, nor is a non-redundant power supply.  Removing these components would impact the function of the overall packaging or is impossible due to the tight integration of the package.
   ///</summary>
   property Removable : Boolean read FRemovable;
   ///<summary>
   ///A physical package is replaceable  if it is possible to replace (FRU or 
   ///upgrade) the element with a physically different one.  For example, some 
   ///computer systems allow the main processor chip to be upgraded to one of a 
   ///higher clock rating. In this case, the processor is said to be replaceable . 
   ///Another example is a power supply package mounted on sliding rails. All 
   ///removable packages are inherently replaceable .
   ///</summary>
   property Replaceable : Boolean read FReplaceable;
   ///<summary>
   ///SecurityBreach is an enumerated, integer-valued property indicating whether a 
   ///physical breach of the frame was attempted but unsuccessful (value=4) or 
   ///attempted and successful (5). Also, the values, "Unknown", "Other" or 
   ///"No Breach", can be specified.
   ///</summary>
   property SecurityBreach : Word read FSecurityBreach;
   ///<summary>
   ///The SecurityStatus property indicates the security setting for external input 
   ///(such as a keyboard) to this computer.
   ///</summary>
   property SecurityStatus : Word read FSecurityStatus;
   ///<summary>
   ///A manufacturer-allocated number used to identify the PhysicalElement.
   ///</summary>
   property SerialNumber : String read FSerialNumber;
   ///<summary>
   ///An array of free-form strings providing more detailed explanations for any of 
   ///the entries in the ServicePhilosophy array. Note, each entry of this array is 
   ///related to the entry in ServicePhilosophy that is located at the same index.
   ///</summary>
   property ServiceDescriptions : String read FServiceDescriptions;
   ///<summary>
   ///ServicePhilosophy is an enumerated, integer-valued array that indicates whether 
   ///the frame is serviced from the top (value=2), front (3), back (4) or side (5), 
   ///whether it has sliding trays (6) or removable sides (7), and/or whether the 
   ///frame is moveable (8), for example, having rollers.
   ///</summary>
   property ServicePhilosophy : Word read FServicePhilosophy;
   ///<summary>
   ///The stock keeping unit number for this physical element.
   ///</summary>
   property SKU : String read FSKU;
   ///<summary>
   ///The SMBIOSAssetTag property indicates the asset tag number of the system 
   ///enclosure.
   ///</summary>
   property SMBIOSAssetTag : String read FSMBIOSAssetTag;
   ///<summary>
   ///The Status property is a string indicating the current status of the object. 
   ///Various operational and non-operational statuses can be defined. Operational 
   ///statuses are "OK", "Degraded" and "Pred Fail". "Pred Fail" indicates that an 
   ///element may be functioning properly but predicting a failure in the near 
   ///future. An example is a SMART-enabled hard drive. Non-operational statuses can 
   ///also be specified. These are "Error", "Starting", "Stopping" and "Service". The 
   ///latter, "Service", could apply during mirror-resilvering of a disk, reload of a 
   ///user permissions list, or other administrative work. Not all such work is on-
   ///line, yet the managed element is neither "OK" nor in one of the other states.
   ///</summary>
   property Status : String read FStatus;
   ///<summary>
   ///The Tag property is a string that uniquely identifies the system 
   ///enclosure.
   ///Example: System Enclosure 1
   ///</summary>
   property Tag : String read FTag;
   ///<summary>
   ///An array of free-form strings providing more information on the ChassisTypes 
   ///array entries. Note, each entry of this array is related to the entry in 
   ///ChassisTypes that is located at the same index.
   ///</summary>
   property TypeDescriptions : String read FTypeDescriptions;
   ///<summary>
   ///A string indicating the version of the physical element.
   ///</summary>
   property Version : String read FVersion;
   ///<summary>
   ///Boolean indicating that the equipment includes a visible alarm.
   ///</summary>
   property VisibleAlarm : Boolean read FVisibleAlarm;
   ///<summary>
   ///The weight of the physical package in pounds.
   ///</summary>
   property Weight : Double read FWeight;
   ///<summary>
   ///The width of the physical package in inches.
   ///</summary>
   property Width : Double read FWidth;
   ///<summary>
   ///The IsCompatible method verifies whether the referenced physical element may be 
   ///contained by or inserted into the physical package. The return value should be 
   ///0 if the request was successfully executed, 1 if the request is not supported 
   ///and some other value if an error occurred.  In a subclass, the set of possible 
   ///return codes could be specified, using a ValueMap qualifier on the method. The 
   ///strings to which the ValueMap contents are 'translated' may also be specified 
   ///in the subclass as a Values array qualifier.
   ///</summary>
   function IsCompatible(ElementToCheck : Variant): Integer;
   procedure SetCollectionIndex(Index:Integer); override;
   constructor Create; overload;
   constructor Create(LoadData:boolean); overload;
  end;


implementation


{TWin32_SystemEnclosure}

 constructor TWin32_SystemEnclosure.Create;
 begin
   Create(True);
 end;

 constructor TWin32_SystemEnclosure.Create(LoadData: boolean);
 begin
   Create(LoadData,'root\CIMV2','Win32_SystemEnclosure');
 end;

 procedure TWin32_SystemEnclosure.SetCollectionIndex(Index: Integer);
 begin
    if (Index>=0) and (Index<=FWmiCollection.Count-1) then
    begin
       FWmiCollectionIndex:=Index;
       FAudibleAlarm                        :=VarBoolNull(GetPropertyValue('AudibleAlarm'));
       FBreachDescription                   :=VarStrNull(GetPropertyValue('BreachDescription'));
       FCableManagementStrategy             :=VarStrNull(GetPropertyValue('CableManagementStrategy'));
       FCaption                             :=VarStrNull(GetPropertyValue('Caption'));
       FChassisTypes                        :=VarWordNull(GetPropertyValue('ChassisTypes'));
       FCreationClassName                   :=VarStrNull(GetPropertyValue('CreationClassName'));
       Unsoported CurrentRequiredOrProduced : SmallInt 
       FDepth                               :=VarDoubleNull(GetPropertyValue('Depth'));
       FDescription                         :=VarStrNull(GetPropertyValue('Description'));
       FHeatGeneration                      :=VarWordNull(GetPropertyValue('HeatGeneration'));
       FHeight                              :=VarDoubleNull(GetPropertyValue('Height'));
       FHotSwappable                        :=VarBoolNull(GetPropertyValue('HotSwappable'));
       FInstallDate                         :=VarDateTimeNull(GetPropertyValue('InstallDate'));
       FLockPresent                         :=VarBoolNull(GetPropertyValue('LockPresent'));
       FManufacturer                        :=VarStrNull(GetPropertyValue('Manufacturer'));
       FModel                               :=VarStrNull(GetPropertyValue('Model'));
       FName                                :=VarStrNull(GetPropertyValue('Name'));
       FNumberOfPowerCords                  :=VarWordNull(GetPropertyValue('NumberOfPowerCords'));
       FOtherIdentifyingInfo                :=VarStrNull(GetPropertyValue('OtherIdentifyingInfo'));
       FPartNumber                          :=VarStrNull(GetPropertyValue('PartNumber'));
       FPoweredOn                           :=VarBoolNull(GetPropertyValue('PoweredOn'));
       FRemovable                           :=VarBoolNull(GetPropertyValue('Removable'));
       FReplaceable                         :=VarBoolNull(GetPropertyValue('Replaceable'));
       FSecurityBreach                      :=VarWordNull(GetPropertyValue('SecurityBreach'));
       FSecurityStatus                      :=VarWordNull(GetPropertyValue('SecurityStatus'));
       FSerialNumber                        :=VarStrNull(GetPropertyValue('SerialNumber'));
       FServiceDescriptions                 :=VarStrNull(GetPropertyValue('ServiceDescriptions'));
       FServicePhilosophy                   :=VarWordNull(GetPropertyValue('ServicePhilosophy'));
       FSKU                                 :=VarStrNull(GetPropertyValue('SKU'));
       FSMBIOSAssetTag                      :=VarStrNull(GetPropertyValue('SMBIOSAssetTag'));
       FStatus                              :=VarStrNull(GetPropertyValue('Status'));
       FTag                                 :=VarStrNull(GetPropertyValue('Tag'));
       FTypeDescriptions                    :=VarStrNull(GetPropertyValue('TypeDescriptions'));
       FVersion                             :=VarStrNull(GetPropertyValue('Version'));
       FVisibleAlarm                        :=VarBoolNull(GetPropertyValue('VisibleAlarm'));
       FWeight                              :=VarDoubleNull(GetPropertyValue('Weight'));
       FWidth                               :=VarDoubleNull(GetPropertyValue('Width'));
    end;
 end;


//not static, OutParams=1, InParams>0
function TWin32_SystemEnclosure.IsCompatible(ElementToCheck : Variant): Integer;
var
  objSWbemLocator : OLEVariant;
  objWMIService   : OLEVariant;
  objInvoker      : OLEVariant;
  ReturnValue     : OLEVariant;
  oEnum           : IEnumvariant;
  colItem         : OLEVariant;
  iValue          : LongWord;
  CurrIndex       : integer;
begin
  Result:=-1;
  objSWbemLocator := CreateOleObject('WbemScripting.SWbemLocator');
  objWMIService   := objSWbemLocator.ConnectServer('localhost','root\CIMV2', '','');
  objInvoker      := objWMIService.InstancesOf('Win32_SystemEnclosure');
  oEnum           := IUnknown(objInvoker._NewEnum) as IEnumVariant;
  CurrIndex       := 0;
  while oEnum.Next(1, colItem, iValue) = 0 do
  begin
  if CurrIndex=FWmiCollectionIndex then
    begin
     ReturnValue:=colItem.IsCompatible(ElementToCheck);
     Result     :=VarIntegerNull(ReturnValue);
     Exit;
    end;
   Inc(CurrIndex);
  end;
end;

end.
